In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

df = pd.read_excel("weathers.xlsx")
df

outlook temperature humidity  windy play
0   overcast         hot     high      0  yes
1   overcast        cool   normal      1  yes
2   overcast        mild     high      1  yes
3   overcast         hot   normal      0  yes
4      rainy        mild     high      0  yes
5      rainy        cool   normal      0  yes
6      rainy        cool   normal      1  yes
7      rainy        mild     high      0   no
8      rainy        mild     high      1   no
9      sunny         hot     high      0   no
10     sunny         hot     high      0   no
11     sunny        mild     high      1   no
12     sunny        cool   normal      1  yes
13     sunny        mild   normal      1  yes
14     rainy        cool     high      1  yes
15     sunny         hot   normal      0   no
16     sunny         hot   normal      0  yes
17     rainy        cool     high      1  yes
18  overcast        mild   normal      0  yes
19  overcast        mild   normal      0   no
20  overcast        mild   normal      1   no

In [ ]:
df1=df.dropna()
df1


outlook temperature humidity  windy play
0   overcast         hot     high      0  yes
1   overcast        cool   normal      1  yes
2   overcast        mild     high      1  yes
3   overcast         hot   normal      0  yes
4      rainy        mild     high      0  yes
5      rainy        cool   normal      0  yes
6      rainy        cool   normal      1  yes
7      rainy        mild     high      0   no
8      rainy        mild     high      1   no
9      sunny         hot     high      0   no
10     sunny         hot     high      0   no
11     sunny        mild     high      1   no
12     sunny        cool   normal      1  yes
13     sunny        mild   normal      1  yes
14     rainy        cool     high      1  yes
15     sunny         hot   normal      0   no
16     sunny         hot   normal      0  yes
17     rainy        cool     high      1  yes
18  overcast        mild   normal      0  yes
19  overcast        mild   normal      0   no
20  overcast        mild   normal      1   no

In [ ]:
df1["outlook"].replace({"overcast":1, "rainy":2, "sunny":3},inplace=True)
df1["temperature"].replace({"mild":0,"hot":1,"cool":2},inplace=True)
df1["humidity"].replace({"high":0,"normal":1},inplace=True)
df1["play"].replace({"no":0,"yes":1},inplace=True)


In [ ]:
x=df1.drop("play",axis=1)
y=df1["play"]
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42, stratify=y)


In [ ]:
gnb_model = GaussianNB()
gnb_model.fit(x_train,y_train)



GaussianNB()

In [ ]:
y_pred = gnb_model.predict(x_test)
cnf_matrix = confusion_matrix(y_pred,y_test)
print("Confusion Matrix:\n",cnf_matrix)
print("-"*60)
acc_score = accuracy_score(y_pred,y_test)
print("Accuracy Score:",acc_score)
print("-"*60)
clf_report = classification_report(y_pred,y_test)
print("Classification Report:\n",clf_report)


Confusion Matrix:
 [[1 1]
 [1 2]]
------------------------------------------------------------
Accuracy Score: 0.6
------------------------------------------------------------
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.67      0.67      0.67         3

    accuracy                           0.60         5
   macro avg       0.58      0.58      0.58         5
weighted avg       0.60      0.60      0.60         5



In [ ]:
y_pred_train = gnb_model.predict(x_train)
cnf_matrix = confusion_matrix(y_pred_train,y_train)
print("Confusion Matrix:\n",cnf_matrix)
print("-"*60)
acc_score = accuracy_score(y_pred_train,y_train)
print("Accuracy Score:",acc_score)
print("-"*60)
clf_report = classification_report(y_pred_train,y_train)
print("Classification Report:\n",clf_report)

Confusion Matrix:
 [[4 2]
 [2 8]]
------------------------------------------------------------
Accuracy Score: 0.75
------------------------------------------------------------
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.67      0.67         6
           1       0.80      0.80      0.80        10

    accuracy                           0.75        16
   macro avg       0.73      0.73      0.73        16
weighted avg       0.75      0.75      0.75        16



In [ ]:
column_names = x.columns
column_names


Index(['outlook', 'temperature', 'humidity', 'windy'], dtype='object')

In [ ]:
outlook_value={'overcast':1, 'rainy':2, 'sunny':3}
temperature_value={'mild':0,'hot':1,'cool':2}
humidity_value={'high':0,'normal':1}


In [ ]:
json_data = {
    'outlook':outlook_value,
    'temperature':temperature_value,
    'humidity':humidity_value
}
json_data


{'outlook': {'overcast': 1, 'rainy': 2, 'sunny': 3},
 'temperature': {'mild': 0, 'hot': 1, 'cool': 2},
 'humidity': {'high': 0, 'normal': 1}}

In [ ]:
import json
with open('DWDM9.json', 'w') as f:
    json.dump(json_data, f)


In [ ]:
outlook='rainy'
temperature='mild'
humidity='high'
windy=1.0


In [ ]:
test_array = np.zeros(len(x.columns))
test_array[0] = json_data['outlook'][outlook]
test_array[1] = json_data['temperature'][temperature]
test_array[2] = json_data['humidity'][humidity]
test_array[3] = windy
test_array


array([2., 0., 0., 1.])

In [ ]:
play=gnb_model.predict([test_array])[0]
if play==1:
    print("Play")
else:
    print("No Play")


No Play
